name = "MI: To The Sky"
author = "TheMade4"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "632fb99682ec5307a8de0cb7e0349f681df0713b921ee40ac7032e0864d6739b"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
